// Change for production or if you want to use it on EXPO mobile
export const API_URL = "http://localhost:9000";

export const GET_FILMS = "GET_FILMS";
export const GET_FILMS_SUCCESS = "GET_FILMS_SUCCESS";
export const GET_FILMS_ERROR = "GET_FILMS_ERROR";

export const GET_SINGLE_FILM = "GET_SINGLE_FILM";
export const GET_SINGLE_FILM_SUCCESS = "GET_SINGLE_FILM_SUCCESS";
export const GET_SINGLE_FILM_ERROR = "GET_SINGLE_FILM_ERROR";

export const GET_CHARACTERS_BY_FILM = "GET_CHARACTERS_BY_FILM";
export const GET_CHARACTERS_BY_FILM_SUCCESS = "GET_CHARACTERS_BY_FILM_SUCCESS";
export const GET_CHARACTERS_BY_FILM_ERROR = "GET_CHARACTERS_BY_FILM_ERROR";

export const GET_PLANETS = "GET_PLANETS";
export const GET_PLANETS_SUCCESS = "GET_PLANETS_SUCCESS";
export const GET_PLANETS_ERROR = "GET_PLANETS_ERROR";

export const GET_SINGLE_PLANET = "GET_SINGLE_PLANET";
export const GET_SINGLE_PLANET_SUCCESS = "GET_SINGLE_PLANET_SUCCESS";
export const GET_SINGLE_PLANET_ERROR = "GET_SINGLE_PLANET_ERROR";

export const GET_RESIDENTS_BY_PLANET = "GET_RESIDENTS_BY_PLANET";
export const GET_RESIDENTS_BY_PLANET_SUCCESS =
  "GET_RESIDENTS_BY_PLANET_SUCCESS";
export const GET_RESIDENTS_BY_PLANET_ERROR = "GET_CHARACTERS_BY_PLANET_ERROR";
